# Generated by Django 4.2.6 on 2023-11-08 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnty', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('total_price', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('phn', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('uname', models.CharField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
                ('adrs', models.CharField(default='', max_length=100)),
                ('available_time', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('utype', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('phn', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('uname', models.CharField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
                ('adrs', models.CharField(default='', max_length=100)),
                ('utype', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_shopdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(default='', max_length=100)),
                ('phn', models.CharField(default='', max_length=100)),
                ('adrs', models.CharField(default='', max_length=100)),
                ('pname', models.CharField(default='', max_length=100)),
                ('amnt', models.CharField(default='', max_length=100)),
                ('qnty', models.CharField(default='', max_length=100)),
                ('files', models.ImageField(default='null.jpeg', upload_to='file')),
                ('img', models.ImageField(default='null.jpeg', upload_to='file')),
                ('status', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('shop_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ayurvedicapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('total_amt', models.CharField(default='', max_length=100)),
                ('card_name', models.CharField(default='', max_length=100)),
                ('card_number', models.CharField(default='', max_length=100)),
                ('card_cvv', models.CharField(default='', max_length=100)),
                ('card_expdate', models.CharField(default='', max_length=100)),
                ('pay_status', models.CharField(default='', max_length=100)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ayurvedicapp.tbl_shopdetails')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ayurvedicapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('payment_status', models.CharField(default='', max_length=30)),
                ('cart_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ayurvedicapp.tb_cart')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ayurvedicapp.tbl_shopdetails')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ayurvedicapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(default='', max_length=100)),
                ('doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ayurvedicapp.tbl_doctor')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ayurvedicapp.tbl_register')),
            ],
        ),
        migrations.AddField(
            model_name='tb_cart',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ayurvedicapp.tbl_shopdetails'),
        ),
        migrations.AddField(
            model_name='tb_cart',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ayurvedicapp.tbl_register'),
        ),
    ]
