# Generated by Django 4.2.6 on 2023-11-08 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_payment',
            name='cart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ayurvedicapp.tbl_order'),
        ),
    ]
