# Generated by Django 4.2.6 on 2023-11-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0002_tbl_payment_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_payment',
            old_name='cart_id',
            new_name='order_id',
        ),
    ]
