# Generated by Django 4.2.6 on 2023-11-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0003_rename_cart_id_tbl_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_payment',
            name='card_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
