# Generated by Django 4.2.6 on 2023-11-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0004_tbl_payment_card_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_order',
            name='order_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
