# Generated by Django 4.2.6 on 2023-11-09 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0005_tbl_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_payment',
            name='product_id',
        ),
    ]
