# Generated by Django 4.2.4 on 2023-11-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0007_tbl_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='doctor_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
