# Generated by Django 4.2.6 on 2023-11-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0010_tbl_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_message',
            name='img',
            field=models.ImageField(default='null.jpeg', upload_to='file'),
        ),
    ]
