# Generated by Django 4.2.6 on 2023-11-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0011_tbl_message_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_message',
            name='img',
            field=models.ImageField(upload_to='file'),
        ),
    ]
