# Generated by Django 4.2.6 on 2023-11-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0012_alter_tbl_message_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_message',
            name='img',
            field=models.ImageField(default='null.jpeg', upload_to='file'),
        ),
    ]
