# Generated by Django 4.2.6 on 2023-11-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0013_alter_tbl_message_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_message',
            name='img',
        ),
    ]
