# Generated by Django 4.2.6 on 2023-12-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0014_remove_tbl_message_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_message',
            name='file',
            field=models.ImageField(default='null.jpeg', upload_to='file'),
        ),
    ]
