# Generated by Django 4.2.6 on 2023-12-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0015_tbl_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_message',
            name='utype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
