# Generated by Django 4.2.6 on 2024-02-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0017_tbl_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_chat',
            old_name='msg',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='tbl_chat',
            old_name='doctor_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='tbl_chat',
            old_name='user_id',
            new_name='sender',
        ),
    ]
