# Generated by Django 4.2.6 on 2024-02-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0018_rename_msg_tbl_chat_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_chat',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
