# Generated by Django 4.2.7 on 2024-03-09 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0019_tbl_chat_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('utype', models.CharField(default='', max_length=100)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ayurvedicapp.tbl_register')),
            ],
        ),
    ]
