# Generated by Django 4.2.7 on 2024-03-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0021_tbl_doctor_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctor_notifications',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ayurvedicapp.tbl_doctor'),
        ),
    ]
