# Generated by Django 4.2.7 on 2024-03-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0022_alter_tbl_doctor_notifications_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_doctor',
            name='profile_image',
            field=models.ImageField(default='default_pro.png', upload_to='doctor_profile'),
        ),
    ]
