# Generated by Django 4.1.4 on 2024-03-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0023_tbl_doctor_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_order',
            name='order_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
