# Generated by Django 4.1.4 on 2024-09-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ayurvedicapp', '0024_tbl_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_notifications',
            name='message',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
